#############################################################################
# Makefile for building: libCustomLoadScreen.so.1.0.0
# Generated by qmake (3.1) (Qt 5.15.17)
# Project:  CustomLoadScreen.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile CustomLoadScreen.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = x86_64-w64-mingw32-gcc
CXX           = x86_64-w64-mingw32-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1y -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/qt -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CustomLoadScreen1.0.0
DISTDIR = /home/endless/Загрузки/customloadscreen-master/.tmp/CustomLoadScreen1.0.0
LINK          = x86_64-w64-mingw32-g++
LFLAGS        = -Wl,-O1 -static -static-libgcc -static-libstdc++ -pipe -O2 -std=gnu++1y -flto=16 -fno-fat-lto-objects -fuse-linker-plugin -shared -fPIC -Wl,-soname,libCustomLoadScreen.so.1
LIBS          = $(SUBLIBS) -ld3d9 -ld3dx9 -lgdi32 -luser32 - /usr/lib/libQt5Core.so -lpthread   
AR            = gcc-ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CustomLoadScreen.cpp \
		loader.cpp \
		llmo/ccallhook.cpp \
		llmo/memsafe.cpp \
		llmo/cshortasm.cpp \
		sys/mman.c \
		d3d9/proxydirectx.cpp \
		d3d9/directx.cpp \
		d3d9/color.cpp \
		d3d9/d3drender.cpp \
		d3d9/texture.cpp \
		d3d9/MenuManager/ContextMenu.cpp \
		d3d9/MenuManager/Listing.cpp \
		d3d9/MenuManager/Menu.cpp \
		d3d9/MenuManager/Node.cpp \
		d3d9/MenuManager/NodeMenu.cpp \
		d3d9/MenuManager/Text.cpp \
		d3d9/MenuManager/VerticalLayout.cpp \
		d3d9/MenuManager/CSlider.cpp \
		CGame/CPed.cpp \
		CGame/CPhysical.cpp \
		CGame/Types.cpp \
		CGame/methods.cpp \
		CGame/CCam.cpp \
		CGame/CCamera.cpp \
		CGame/CVehicle.cpp moc_CustomLoadScreen.cpp \
		moc_directx.cpp \
		moc_texture.cpp \
		moc_ContextMenu.cpp \
		moc_Listing.cpp \
		moc_Menu.cpp \
		moc_Node.cpp \
		moc_NodeMenu.cpp \
		moc_Text.cpp \
		moc_VerticalLayout.cpp \
		moc_CSlider.cpp
OBJECTS       = CustomLoadScreen.o \
		loader.o \
		ccallhook.o \
		memsafe.o \
		cshortasm.o \
		mman.o \
		proxydirectx.o \
		directx.o \
		color.o \
		d3drender.o \
		texture.o \
		ContextMenu.o \
		Listing.o \
		Menu.o \
		Node.o \
		NodeMenu.o \
		Text.o \
		VerticalLayout.o \
		CSlider.o \
		CPed.o \
		CPhysical.o \
		Types.o \
		methods.o \
		CCam.o \
		CCamera.o \
		CVehicle.o \
		moc_CustomLoadScreen.o \
		moc_directx.o \
		moc_texture.o \
		moc_ContextMenu.o \
		moc_Listing.o \
		moc_Menu.o \
		moc_Node.o \
		moc_NodeMenu.o \
		moc_Text.o \
		moc_VerticalLayout.o \
		moc_CSlider.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		CustomLoadScreen.pro CustomLoadScreen.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/memsafe.h \
		llmo/cshortasm.h \
		sys/mman.h \
		d3d9/proxydirectx.h \
		d3d9/directx.h \
		d3d9/color.h \
		d3d9/d3drender.h \
		d3d9/texture.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/CSlider.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		CGame/methods.h \
		CGame/CCam.h \
		CGame/CCamera.h CustomLoadScreen.cpp \
		loader.cpp \
		llmo/ccallhook.cpp \
		llmo/memsafe.cpp \
		llmo/cshortasm.cpp \
		sys/mman.c \
		d3d9/proxydirectx.cpp \
		d3d9/directx.cpp \
		d3d9/color.cpp \
		d3d9/d3drender.cpp \
		d3d9/texture.cpp \
		d3d9/MenuManager/ContextMenu.cpp \
		d3d9/MenuManager/Listing.cpp \
		d3d9/MenuManager/Menu.cpp \
		d3d9/MenuManager/Node.cpp \
		d3d9/MenuManager/NodeMenu.cpp \
		d3d9/MenuManager/Text.cpp \
		d3d9/MenuManager/VerticalLayout.cpp \
		d3d9/MenuManager/CSlider.cpp \
		CGame/CPed.cpp \
		CGame/CPhysical.cpp \
		CGame/Types.cpp \
		CGame/methods.cpp \
		CGame/CCam.cpp \
		CGame/CCamera.cpp \
		CGame/CVehicle.cpp
QMAKE_TARGET  = CustomLoadScreen
DESTDIR       = ../
TARGET        = libCustomLoadScreen.so.1.0.0
TARGETA       = ../libCustomLoadScreen.a
TARGET0       = libCustomLoadScreen.so
TARGETD       = libCustomLoadScreen.so.1.0.0
TARGET1       = libCustomLoadScreen.so.1
TARGET2       = libCustomLoadScreen.so.1.0


first: all
####### Build rules

../libCustomLoadScreen.so.1.0.0:  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../ || mkdir -p ../
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) ../$(TARGET)
	-$(MOVE) $(TARGET) ../$(TARGET)
	-$(DEL_FILE) ../$(TARGET0)
	-$(DEL_FILE) ../$(TARGET1)
	-$(DEL_FILE) ../$(TARGET2)
	-$(MOVE) $(TARGET0) ../$(TARGET0)
	-$(MOVE) $(TARGET1) ../$(TARGET1)
	-$(MOVE) $(TARGET2) ../$(TARGET2)



staticlib: ../libCustomLoadScreen.a

../libCustomLoadScreen.a:  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: CustomLoadScreen.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		CustomLoadScreen.pro
	$(QMAKE) -o Makefile CustomLoadScreen.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_ltcg.prf:
/usr/lib/qt/mkspecs/features/ltcg.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
CustomLoadScreen.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile CustomLoadScreen.pro

qmake_all: FORCE


all: Makefile ../libCustomLoadScreen.so.1.0.0

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CustomLoadScreen.h loader.h llmo/ccallhook.h llmo/memsafe.h llmo/cshortasm.h sys/mman.h d3d9/proxydirectx.h d3d9/directx.h d3d9/color.h d3d9/d3drender.h d3d9/texture.h d3d9/MenuManager/ContextMenu.h d3d9/MenuManager/Listing.h d3d9/MenuManager/Menu.h d3d9/MenuManager/Node.h d3d9/MenuManager/NodeMenu.h d3d9/MenuManager/Text.h d3d9/MenuManager/VerticalLayout.h d3d9/MenuManager/CSlider.h CGame/Types.h CGame/CPlaceable.h CGame/CEntity.h CGame/CPhysical.h CGame/CObject.h CGame/CHAnimIFrame.h CGame/CBone.h CGame/CPedIK.h CGame/CParticleData.h CGame/CWeaponSlot.h CGame/CPed.h CGame/CVehicle.h CGame/methods.h CGame/CCam.h CGame/CCamera.h $(DISTDIR)/
	$(COPY_FILE) --parents CustomLoadScreen.cpp loader.cpp llmo/ccallhook.cpp llmo/memsafe.cpp llmo/cshortasm.cpp sys/mman.c d3d9/proxydirectx.cpp d3d9/directx.cpp d3d9/color.cpp d3d9/d3drender.cpp d3d9/texture.cpp d3d9/MenuManager/ContextMenu.cpp d3d9/MenuManager/Listing.cpp d3d9/MenuManager/Menu.cpp d3d9/MenuManager/Node.cpp d3d9/MenuManager/NodeMenu.cpp d3d9/MenuManager/Text.cpp d3d9/MenuManager/VerticalLayout.cpp d3d9/MenuManager/CSlider.cpp CGame/CPed.cpp CGame/CPhysical.cpp CGame/Types.cpp CGame/methods.cpp CGame/CCam.cpp CGame/CCamera.cpp CGame/CVehicle.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../$(TARGET) 
	-$(DEL_FILE) ../$(TARGET0) ../$(TARGET1) ../$(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	x86_64-w64-mingw32-g++ -pipe -O2 -std=gnu++1y -flto -fno-fat-lto-objects -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_CustomLoadScreen.cpp moc_directx.cpp moc_texture.cpp moc_ContextMenu.cpp moc_Listing.cpp moc_Menu.cpp moc_Node.cpp moc_NodeMenu.cpp moc_Text.cpp moc_VerticalLayout.cpp moc_CSlider.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_CustomLoadScreen.cpp moc_directx.cpp moc_texture.cpp moc_ContextMenu.cpp moc_Listing.cpp moc_Menu.cpp moc_Node.cpp moc_NodeMenu.cpp moc_Text.cpp moc_VerticalLayout.cpp moc_CSlider.cpp
moc_CustomLoadScreen.cpp: CustomLoadScreen.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/d3drender.h \
		d3d9/color.h \
		d3d9/texture.h \
		d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/CSlider.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include CustomLoadScreen.h -o moc_CustomLoadScreen.cpp

moc_directx.cpp: d3d9/directx.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/directx.h -o moc_directx.cpp

moc_texture.cpp: d3d9/texture.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/texture.h -o moc_texture.cpp

moc_ContextMenu.cpp: d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/MenuManager/Text.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/MenuManager/ContextMenu.h -o moc_ContextMenu.cpp

moc_Listing.cpp: d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/MenuManager/Listing.h -o moc_Listing.cpp

moc_Menu.cpp: d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Text.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/MenuManager/Menu.h -o moc_Menu.cpp

moc_Node.cpp: d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/MenuManager/Node.h -o moc_Node.cpp

moc_NodeMenu.cpp: d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/MenuManager/NodeMenu.h -o moc_NodeMenu.cpp

moc_Text.cpp: d3d9/MenuManager/Text.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/MenuManager/Text.h -o moc_Text.cpp

moc_VerticalLayout.cpp: d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/MenuManager/VerticalLayout.h -o moc_VerticalLayout.cpp

moc_CSlider.cpp: d3d9/MenuManager/CSlider.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/endless/Загрузки/customloadscreen-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/endless/Загрузки/customloadscreen-master -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include d3d9/MenuManager/CSlider.h -o moc_CSlider.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

CustomLoadScreen.o: CustomLoadScreen.cpp CustomLoadScreen.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/d3drender.h \
		d3d9/color.h \
		d3d9/texture.h \
		d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/CSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CustomLoadScreen.o CustomLoadScreen.cpp

loader.o: loader.cpp loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		CustomLoadScreen.h \
		d3d9/d3drender.h \
		d3d9/color.h \
		d3d9/texture.h \
		d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/CSlider.h \
		d3d9/proxydirectx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loader.o loader.cpp

ccallhook.o: llmo/ccallhook.cpp llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ccallhook.o llmo/ccallhook.cpp

memsafe.o: llmo/memsafe.cpp llmo/memsafe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memsafe.o llmo/memsafe.cpp

cshortasm.o: llmo/cshortasm.cpp llmo/cshortasm.h \
		sys/mman.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cshortasm.o llmo/cshortasm.cpp

mman.o: sys/mman.c sys/mman.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mman.o sys/mman.c

proxydirectx.o: d3d9/proxydirectx.cpp d3d9/proxydirectx.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/d3drender.h \
		d3d9/color.h \
		d3d9/texture.h \
		d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/CSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o proxydirectx.o d3d9/proxydirectx.cpp

directx.o: d3d9/directx.cpp d3d9/directx.h \
		d3d9/proxydirectx.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/d3drender.h \
		d3d9/color.h \
		d3d9/texture.h \
		d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/CSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o directx.o d3d9/directx.cpp

color.o: d3d9/color.cpp d3d9/color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o color.o d3d9/color.cpp

d3drender.o: d3d9/d3drender.cpp d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o d3drender.o d3d9/d3drender.cpp

texture.o: d3d9/texture.cpp d3d9/texture.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o texture.o d3d9/texture.cpp

ContextMenu.o: d3d9/MenuManager/ContextMenu.cpp d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ContextMenu.o d3d9/MenuManager/ContextMenu.cpp

Listing.o: d3d9/MenuManager/Listing.cpp d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Listing.o d3d9/MenuManager/Listing.cpp

Menu.o: d3d9/MenuManager/Menu.cpp d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Text.h \
		d3d9/proxydirectx.h \
		d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/CSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Menu.o d3d9/MenuManager/Menu.cpp

Node.o: d3d9/MenuManager/Node.cpp d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h \
		d3d9/proxydirectx.h \
		d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/CSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Node.o d3d9/MenuManager/Node.cpp

NodeMenu.o: d3d9/MenuManager/NodeMenu.cpp d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/MenuManager/Menu.h \
		d3d9/MenuManager/Node.h \
		d3d9/texture.h \
		d3d9/MenuManager/ContextMenu.h \
		d3d9/MenuManager/Text.h \
		d3d9/proxydirectx.h \
		d3d9/MenuManager/Listing.h \
		d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/CSlider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NodeMenu.o d3d9/MenuManager/NodeMenu.cpp

Text.o: d3d9/MenuManager/Text.cpp d3d9/MenuManager/Text.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Text.o d3d9/MenuManager/Text.cpp

VerticalLayout.o: d3d9/MenuManager/VerticalLayout.cpp d3d9/MenuManager/VerticalLayout.h \
		d3d9/MenuManager/Node.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VerticalLayout.o d3d9/MenuManager/VerticalLayout.cpp

CSlider.o: d3d9/MenuManager/CSlider.cpp d3d9/MenuManager/CSlider.h \
		d3d9/MenuManager/Text.h \
		d3d9/MenuManager/NodeMenu.h \
		d3d9/d3drender.h \
		loader.h \
		llmo/ccallhook.h \
		llmo/cshortasm.h \
		sys/mman.h \
		llmo/memsafe.h \
		d3d9/directx.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CPhysical.h \
		CGame/CObject.h \
		CGame/CHAnimIFrame.h \
		CGame/CBone.h \
		CGame/CPedIK.h \
		CGame/CParticleData.h \
		CGame/CWeaponSlot.h \
		CGame/CPed.h \
		CGame/CVehicle.h \
		d3d9/color.h \
		d3d9/texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CSlider.o d3d9/MenuManager/CSlider.cpp

CPed.o: CGame/CPed.cpp CGame/CPed.h \
		CGame/Types.h \
		CGame/CObject.h \
		CGame/CPhysical.h \
		CGame/CEntity.h \
		CGame/CPlaceable.h \
		CGame/CPedIK.h \
		CGame/CWeaponSlot.h \
		CGame/CVehicle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPed.o CGame/CPed.cpp

CPhysical.o: CGame/CPhysical.cpp CGame/CPhysical.h \
		CGame/Types.h \
		CGame/CEntity.h \
		CGame/CPlaceable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPhysical.o CGame/CPhysical.cpp

Types.o: CGame/Types.cpp CGame/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Types.o CGame/Types.cpp

methods.o: CGame/methods.cpp CGame/methods.h \
		CGame/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o methods.o CGame/methods.cpp

CCam.o: CGame/CCam.cpp CGame/CCam.h \
		CGame/Types.h \
		CGame/CEntity.h \
		CGame/CPlaceable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CCam.o CGame/CCam.cpp

CCamera.o: CGame/CCamera.cpp CGame/CCamera.h \
		CGame/Types.h \
		CGame/CPlaceable.h \
		CGame/CEntity.h \
		CGame/CCam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CCamera.o CGame/CCamera.cpp

CVehicle.o: CGame/CVehicle.cpp CGame/CVehicle.h \
		CGame/Types.h \
		CGame/CPhysical.h \
		CGame/CEntity.h \
		CGame/CPlaceable.h \
		CGame/CPed.h \
		CGame/CObject.h \
		CGame/CPedIK.h \
		CGame/CWeaponSlot.h \
		CGame/CCamera.h \
		CGame/CCam.h \
		CGame/methods.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CVehicle.o CGame/CVehicle.cpp

moc_CustomLoadScreen.o: moc_CustomLoadScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CustomLoadScreen.o moc_CustomLoadScreen.cpp

moc_directx.o: moc_directx.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_directx.o moc_directx.cpp

moc_texture.o: moc_texture.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_texture.o moc_texture.cpp

moc_ContextMenu.o: moc_ContextMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ContextMenu.o moc_ContextMenu.cpp

moc_Listing.o: moc_Listing.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Listing.o moc_Listing.cpp

moc_Menu.o: moc_Menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Menu.o moc_Menu.cpp

moc_Node.o: moc_Node.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Node.o moc_Node.cpp

moc_NodeMenu.o: moc_NodeMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NodeMenu.o moc_NodeMenu.cpp

moc_Text.o: moc_Text.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Text.o moc_Text.cpp

moc_VerticalLayout.o: moc_VerticalLayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VerticalLayout.o moc_VerticalLayout.cpp

moc_CSlider.o: moc_CSlider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CSlider.o moc_CSlider.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

